
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./symfony:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html
    expose:
      - "9000" # Este es el puerto FPM interno
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,dynamodb,sqs,lambda,sns  # agregamos dynamodb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=20
    ports:
      - "4566:4566"  # Puerto de acceso a los servicios de AWS simulados
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./function.zip:/tmp/function.zip  # <--- Aquí el ZIP de Lambda 
      - ./localstack/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
      - ./localstack/init-dynamodb.sh:/etc/localstack/init/ready.d/init-dynamodb.sh    
      - ./localstack/init-lambda.sh:/etc/localstack/init/ready.d/init-lambda.sh
      - ./localstack/init-sns.sh:/etc/localstack/init/ready.d/init-sns.sh
      