framework:
    messenger:
        transports:
            sns_sqs:
                dsn: 'sqs://%env(AWS_SQS_KEY)%:%env(AWS_SQS_SECRET)%@default'
                options:
                    queue_name: 'sns-queue'
                    region: '%env(AWS_SQS_REGION)%'
                    endpoint: '%env(AWS_SQS_ENDPOINT)%'
